// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkL1PHdRDmpf34swJfq4jZH7FQlSFRQaA',
    appId: '1:402393964286:web:df3effd3c22981edf7cfaf',
    messagingSenderId: '402393964286',
    projectId: 'neurosync-362a9',
    authDomain: 'neurosync-362a9.firebaseapp.com',
    storageBucket: 'neurosync-362a9.firebasestorage.app',
    measurementId: 'G-BJK6XNSKRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBXZ7GhfUhDFyOWfllS_Qu8oGBlFBAIs',
    appId: '1:402393964286:android:8b4440f3b88e2936f7cfaf',
    messagingSenderId: '402393964286',
    projectId: 'neurosync-362a9',
    storageBucket: 'neurosync-362a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvU4zmsMpGu7rH-wQXhPvSsGMpccH_c5U',
    appId: '1:402393964286:ios:f027fd7503d765a8f7cfaf',
    messagingSenderId: '402393964286',
    projectId: 'neurosync-362a9',
    storageBucket: 'neurosync-362a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvU4zmsMpGu7rH-wQXhPvSsGMpccH_c5U',
    appId: '1:402393964286:ios:f027fd7503d765a8f7cfaf',
    messagingSenderId: '402393964286',
    projectId: 'neurosync-362a9',
    storageBucket: 'neurosync-362a9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkL1PHdRDmpf34swJfq4jZH7FQlSFRQaA',
    appId: '1:402393964286:web:b3d60c1761a5c541f7cfaf',
    messagingSenderId: '402393964286',
    projectId: 'neurosync-362a9',
    authDomain: 'neurosync-362a9.firebaseapp.com',
    storageBucket: 'neurosync-362a9.firebasestorage.app',
    measurementId: 'G-Y9CP4S6Q3G',
  );
}
